# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='quotes',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
