# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-21 17:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20160801_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='scheduled',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 21, 17, 46, 26, 101426, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
