# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_quote_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='scheduled',
            field=models.DateTimeField(blank=True),
        ),
    ]
