# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-04 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_auto_20160904_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='scheduled',
            field=models.DateTimeField(null=True),
        ),
    ]
